### ISSUE TITLE
Scrolling down while the page is loading hides the header

### ISSUE THREAD

**Issue by vinnymac** [LeKoArts/gatsby-starter-portfolio-emma#4] opened 2017-11-13 16:21 UTC
If you scroll down and then scroll back up once the page has loaded you can't see the header since it is [hidden](https://github.com/LeKoArts/gatsby-starter-portfolio-emma/blob/master/src/components/Navigation/Headroom.scss#L35) by the `headroom--unpinned` class applied by the Headroom dependency.

You can reproduce this on the [demo site](https://embalmer-glues-43220.netlify.com/).

Not sure what the right thing to do is, I wasn't able to reproduce this issue on the [Headroom demo site](https://kyleamathews.github.io/react-headroom/), so I wonder if it has something to do with the way it is being used here.

**Comment by LeKoArts** [comment] 2017-11-14 10:30
The issue would be resolved if I'd remove the Fade Component / Fading but I actually like the effect in the navigation.

Did this issue happen to you multiple times while not "forcing" it? Because I had problems to reproduce it even though I know how to reproduce it as it's uncommon (for me) to instantly scroll down when the site is loading.

Maybe there's a problem with anchors?

**Comment by vinnymac** [comment] 2017-11-14 16:52
Interestingly enough I have trouble reproducing it in the latest firefox, but not the latest chrome. Removing the `Fade` component doesn't seem to have any effect on whether or not I can reproduce the issue in chrome.

**Comment by LeKoArts** [comment] 2017-11-14 19:00
Well I can't reproduce it 😅 
Maybe my assumption with ``Fade`` was wrong but I could only think about the issue being that the Fade animation doesn't get triggered. Mh...

**Comment by LeKoArts** [comment] 2017-12-25 11:05
Can't reproduce it anymore also on latest Chrome. I'm closing this issue now but if someone stumbles across this issue again let me know. Maybe it's something with ``react-headroom``.

**Closed by LeKoArts** 2017-12-25 11:05 UTC
Labels: bug
